/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AddOnInputArgs,
    AddOnInputArgsFromJSON,
    AddOnInputArgsFromJSONTyped,
    AddOnInputArgsToJSON,
} from './AddOnInputArgs';

/**
 * 
 * @export
 * @interface AddAddOnsToPricePlanInput
 */
export interface AddAddOnsToPricePlanInput {
    /**
     * List of add ons to add
     * @type {Array<AddOnInputArgs>}
     * @memberof AddAddOnsToPricePlanInput
     */
    addOns: Array<AddOnInputArgs>;
}

export function AddAddOnsToPricePlanInputFromJSON(json: any): AddAddOnsToPricePlanInput {
    return AddAddOnsToPricePlanInputFromJSONTyped(json, false);
}

export function AddAddOnsToPricePlanInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddAddOnsToPricePlanInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addOns': ((json['add_ons'] as Array<any>).map(AddOnInputArgsFromJSON)),
    };
}

export function AddAddOnsToPricePlanInputToJSON(value?: AddAddOnsToPricePlanInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'add_ons': ((value.addOns as Array<any>).map(AddOnInputArgsToJSON)),
    };
}

