/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FeatureInputArgs,
    FeatureInputArgsFromJSON,
    FeatureInputArgsFromJSONTyped,
    FeatureInputArgsToJSON,
} from './FeatureInputArgs';
import {
    LimitInputArgs,
    LimitInputArgsFromJSON,
    LimitInputArgsFromJSONTyped,
    LimitInputArgsToJSON,
} from './LimitInputArgs';

/**
 * 
 * @export
 * @interface AddFeaturesToPricePlanInput
 */
export interface AddFeaturesToPricePlanInput {
    /**
     * List of new limits to add
     * @type {Array<LimitInputArgs>}
     * @memberof AddFeaturesToPricePlanInput
     */
    limits?: Array<LimitInputArgs>;
    /**
     * List of new features to add
     * @type {Array<FeatureInputArgs>}
     * @memberof AddFeaturesToPricePlanInput
     */
    features?: Array<FeatureInputArgs>;
}

export function AddFeaturesToPricePlanInputFromJSON(json: any): AddFeaturesToPricePlanInput {
    return AddFeaturesToPricePlanInputFromJSONTyped(json, false);
}

export function AddFeaturesToPricePlanInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddFeaturesToPricePlanInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'limits': !exists(json, 'limits') ? undefined : ((json['limits'] as Array<any>).map(LimitInputArgsFromJSON)),
        'features': !exists(json, 'features') ? undefined : ((json['features'] as Array<any>).map(FeatureInputArgsFromJSON)),
    };
}

export function AddFeaturesToPricePlanInputToJSON(value?: AddFeaturesToPricePlanInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'limits': value.limits === undefined ? undefined : ((value.limits as Array<any>).map(LimitInputArgsToJSON)),
        'features': value.features === undefined ? undefined : ((value.features as Array<any>).map(FeatureInputArgsToJSON)),
    };
}

