/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankAccountInfo
 */
export interface BankAccountInfo {
    /**
     * 
     * @type {string}
     * @memberof BankAccountInfo
     */
    externalId?: string;
    /**
     * Country the bank account is in.
     * @type {string}
     * @memberof BankAccountInfo
     */
    country?: string;
    /**
     * Bank account type. E.g. Savings/Checking
     * @type {string}
     * @memberof BankAccountInfo
     */
    accountType?: string;
    /**
     * Last 4 digits of the bank account number.
     * @type {string}
     * @memberof BankAccountInfo
     */
    last4?: string;
    /**
     * Name of the bank
     * @type {string}
     * @memberof BankAccountInfo
     */
    bankName?: string;
    /**
     * Routing number for the bank accopunt
     * @type {number}
     * @memberof BankAccountInfo
     */
    routingNumber?: number;
}

export function BankAccountInfoFromJSON(json: any): BankAccountInfo {
    return BankAccountInfoFromJSONTyped(json, false);
}

export function BankAccountInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccountInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'externalId': !exists(json, 'external_id') ? undefined : json['external_id'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'accountType': !exists(json, 'account_type') ? undefined : json['account_type'],
        'last4': !exists(json, 'last4') ? undefined : json['last4'],
        'bankName': !exists(json, 'bank_name') ? undefined : json['bank_name'],
        'routingNumber': !exists(json, 'routing_number') ? undefined : json['routing_number'],
    };
}

export function BankAccountInfoToJSON(value?: BankAccountInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'external_id': value.externalId,
        'country': value.country,
        'account_type': value.accountType,
        'last4': value.last4,
        'bank_name': value.bankName,
        'routing_number': value.routingNumber,
    };
}

