/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingCycleDate
 */
export interface BillingCycleDate {
    /**
     * 
     * @type {Date}
     * @memberof BillingCycleDate
     */
    cycleStart: Date;
    /**
     * 
     * @type {Date}
     * @memberof BillingCycleDate
     */
    cycleEnd: Date;
}

export function BillingCycleDateFromJSON(json: any): BillingCycleDate {
    return BillingCycleDateFromJSONTyped(json, false);
}

export function BillingCycleDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingCycleDate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cycleStart': (new Date(json['cycle_start'])),
        'cycleEnd': (new Date(json['cycle_end'])),
    };
}

export function BillingCycleDateToJSON(value?: BillingCycleDate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cycle_start': (value.cycleStart.toISOString()),
        'cycle_end': (value.cycleEnd.toISOString()),
    };
}

