/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactInfo
 */
export interface ContactInfo {
    /**
     * 
     * @type {string}
     * @memberof ContactInfo
     */
    addressLine1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactInfo
     */
    addressLine2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactInfo
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactInfo
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactInfo
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactInfo
     */
    zipcode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactInfo
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactInfo
     */
    logoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactInfo
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactInfo
     */
    secondaryEmails?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactInfo
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactInfo
     */
    legalName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactInfo
     */
    vatId?: string | null;
}

export function ContactInfoFromJSON(json: any): ContactInfo {
    return ContactInfoFromJSONTyped(json, false);
}

export function ContactInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addressLine1': !exists(json, 'address_line_1') ? undefined : json['address_line_1'],
        'addressLine2': !exists(json, 'address_line_2') ? undefined : json['address_line_2'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'zipcode': !exists(json, 'zipcode') ? undefined : json['zipcode'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'logoUrl': !exists(json, 'logo_url') ? undefined : json['logo_url'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'secondaryEmails': !exists(json, 'secondary_emails') ? undefined : json['secondary_emails'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'legalName': !exists(json, 'legal_name') ? undefined : json['legal_name'],
        'vatId': !exists(json, 'vat_id') ? undefined : json['vat_id'],
    };
}

export function ContactInfoToJSON(value?: ContactInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address_line_1': value.addressLine1,
        'address_line_2': value.addressLine2,
        'city': value.city,
        'state': value.state,
        'country': value.country,
        'zipcode': value.zipcode,
        'url': value.url,
        'logo_url': value.logoUrl,
        'email': value.email,
        'secondary_emails': value.secondaryEmails,
        'phone': value.phone,
        'legal_name': value.legalName,
        'vat_id': value.vatId,
    };
}

