/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Customer1,
    Customer1FromJSON,
    Customer1FromJSONTyped,
    Customer1ToJSON,
} from './Customer1';
import {
    PricePlan1,
    PricePlan1FromJSON,
    PricePlan1FromJSONTyped,
    PricePlan1ToJSON,
} from './PricePlan1';

/**
 * 
 * @export
 * @interface Coupon1
 */
export interface Coupon1 {
    /**
     * Customer facing code that can be used to apply coupon.
     * @type {string}
     * @memberof Coupon1
     */
    code?: string | null;
    /**
     * The amount of discount to give based on discount_type
     * @type {number}
     * @memberof Coupon1
     */
    discountAmount: number;
    /**
     * 
     * @type {any}
     * @memberof Coupon1
     */
    readonly discountType?: any | null;
    /**
     * UI-friendly name used for data display. Defaults to `name`.
     * @type {string}
     * @memberof Coupon1
     */
    displayName?: string;
    /**
     * The time when the coupon will stop being effective one its applied.
     * @type {number}
     * @memberof Coupon1
     */
    durationLength?: number | null;
    /**
     * The unit time unit to apply to the specified duration length.
     * @type {string}
     * @memberof Coupon1
     */
    durationUnit?: string | null;
    /**
     * 
     * @type {Array<Customer1>}
     * @memberof Coupon1
     */
    excludedCustomers?: Array<Customer1>;
    /**
     * 
     * @type {Array<PricePlan1>}
     * @memberof Coupon1
     */
    excludedPricePlans?: Array<PricePlan1>;
    /**
     * ISO-8601 formatted timestamp that defines after what timestamp this coupon cannot be applied.
     * @type {Date}
     * @memberof Coupon1
     */
    expirationTime?: Date | null;
    /**
     * 
     * @type {any}
     * @memberof Coupon1
     */
    readonly frequency?: any | null;
    /**
     * True if prorate at end of duration, false otherwise
     * @type {boolean}
     * @memberof Coupon1
     */
    isEndProrated?: boolean | null;
    /**
     * True if prorate at application date, false otherwise
     * @type {boolean}
     * @memberof Coupon1
     */
    isStartProrated?: boolean | null;
    /**
     * The maximum number of times this coupon can be used.
     * @type {number}
     * @memberof Coupon1
     */
    maxUses?: number | null;
    /**
     * Unique name identifier.
     * @type {string}
     * @memberof Coupon1
     */
    readonly name: string;
}

export function Coupon1FromJSON(json: any): Coupon1 {
    return Coupon1FromJSONTyped(json, false);
}

export function Coupon1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Coupon1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'discountAmount': json['discount_amount'],
        'discountType': !exists(json, 'discount_type') ? undefined : json['discount_type'],
        'displayName': !exists(json, 'display_name') ? undefined : json['display_name'],
        'durationLength': !exists(json, 'duration_length') ? undefined : json['duration_length'],
        'durationUnit': !exists(json, 'duration_unit') ? undefined : json['duration_unit'],
        'excludedCustomers': !exists(json, 'excluded_customers') ? undefined : ((json['excluded_customers'] as Array<any>).map(Customer1FromJSON)),
        'excludedPricePlans': !exists(json, 'excluded_price_plans') ? undefined : ((json['excluded_price_plans'] as Array<any>).map(PricePlan1FromJSON)),
        'expirationTime': !exists(json, 'expiration_time') ? undefined : (json['expiration_time'] === null ? null : new Date(json['expiration_time'])),
        'frequency': !exists(json, 'frequency') ? undefined : json['frequency'],
        'isEndProrated': !exists(json, 'is_end_prorated') ? undefined : json['is_end_prorated'],
        'isStartProrated': !exists(json, 'is_start_prorated') ? undefined : json['is_start_prorated'],
        'maxUses': !exists(json, 'max_uses') ? undefined : json['max_uses'],
        'name': json['name'],
    };
}

export function Coupon1ToJSON(value?: Coupon1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'discount_amount': value.discountAmount,
        'display_name': value.displayName,
        'duration_length': value.durationLength,
        'duration_unit': value.durationUnit,
        'excluded_customers': value.excludedCustomers === undefined ? undefined : ((value.excludedCustomers as Array<any>).map(Customer1ToJSON)),
        'excluded_price_plans': value.excludedPricePlans === undefined ? undefined : ((value.excludedPricePlans as Array<any>).map(PricePlan1ToJSON)),
        'expiration_time': value.expirationTime === undefined ? undefined : (value.expirationTime === null ? null : value.expirationTime.toISOString()),
        'is_end_prorated': value.isEndProrated,
        'is_start_prorated': value.isStartProrated,
        'max_uses': value.maxUses,
    };
}

