/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCreditTopOffPlanInputArgs
 */
export interface CreateCreditTopOffPlanInputArgs {
    /**
     * The threshold in amount of credits at which the balance will be topped off.
     * @type {number}
     * @memberof CreateCreditTopOffPlanInputArgs
     */
    triggerAmount: number;
    /**
     * Price for the grant, in lowest denomination (i.e cents).
     * @type {number}
     * @memberof CreateCreditTopOffPlanInputArgs
     */
    price: number;
    /**
     * Amount of credits that are granted in a single top off.
     * @type {number}
     * @memberof CreateCreditTopOffPlanInputArgs
     */
    grantAmount: number;
    /**
     * Time length unit for the default expiration for credits granted in a top off.
     * @type {string}
     * @memberof CreateCreditTopOffPlanInputArgs
     */
    expirationUnit?: string;
    /**
     * Time length of the default expiration for credits granted in a top off.
     * @type {number}
     * @memberof CreateCreditTopOffPlanInputArgs
     */
    expirationLength?: number;
}

export function CreateCreditTopOffPlanInputArgsFromJSON(json: any): CreateCreditTopOffPlanInputArgs {
    return CreateCreditTopOffPlanInputArgsFromJSONTyped(json, false);
}

export function CreateCreditTopOffPlanInputArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCreditTopOffPlanInputArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'triggerAmount': json['trigger_amount'],
        'price': json['price'],
        'grantAmount': json['grant_amount'],
        'expirationUnit': !exists(json, 'expiration_unit') ? undefined : json['expiration_unit'],
        'expirationLength': !exists(json, 'expiration_length') ? undefined : json['expiration_length'],
    };
}

export function CreateCreditTopOffPlanInputArgsToJSON(value?: CreateCreditTopOffPlanInputArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'trigger_amount': value.triggerAmount,
        'price': value.price,
        'grant_amount': value.grantAmount,
        'expiration_unit': value.expirationUnit,
        'expiration_length': value.expirationLength,
    };
}

