/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAdhocChargeArgs
 */
export interface CreateAdhocChargeArgs {
    /**
     * The total price for this adhoc charge
     * @type {number}
     * @memberof CreateAdhocChargeArgs
     */
    totalPrice: number;
    /**
     * The quantity associated with this adhoc charge
     * @type {number}
     * @memberof CreateAdhocChargeArgs
     */
    quantity: number;
    /**
     * The invoice item description associated with this adhoc charge
     * @type {string}
     * @memberof CreateAdhocChargeArgs
     */
    itemDescription?: string;
    /**
     * The time when this adhoc charge was made. Should be within an uninvoiced billing cycle.
     * @type {Date}
     * @memberof CreateAdhocChargeArgs
     */
    chargeTime: Date;
    /**
     * The item name associated with this adhoc charge
     * @type {string}
     * @memberof CreateAdhocChargeArgs
     */
    itemName: string;
    /**
     * The invoice item display name associated with this adhoc charge
     * @type {string}
     * @memberof CreateAdhocChargeArgs
     */
    itemDisplayName?: string;
}

export function CreateAdhocChargeArgsFromJSON(json: any): CreateAdhocChargeArgs {
    return CreateAdhocChargeArgsFromJSONTyped(json, false);
}

export function CreateAdhocChargeArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAdhocChargeArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalPrice': json['total_price'],
        'quantity': json['quantity'],
        'itemDescription': !exists(json, 'item_description') ? undefined : json['item_description'],
        'chargeTime': (new Date(json['charge_time'])),
        'itemName': json['item_name'],
        'itemDisplayName': !exists(json, 'item_display_name') ? undefined : json['item_display_name'],
    };
}

export function CreateAdhocChargeArgsToJSON(value?: CreateAdhocChargeArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total_price': value.totalPrice,
        'quantity': value.quantity,
        'item_description': value.itemDescription,
        'charge_time': (value.chargeTime.toISOString()),
        'item_name': value.itemName,
        'item_display_name': value.itemDisplayName,
    };
}

