/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditTopOffPlan
 */
export interface CreditTopOffPlan {
    /**
     * Unique identifier of this top off plan.
     * @type {string}
     * @memberof CreditTopOffPlan
     */
    uuid?: string;
    /**
     * The threshold in amount of credits at which the balance will be topped off.
     * @type {number}
     * @memberof CreditTopOffPlan
     */
    triggerAmount: number;
    /**
     * Amount of credits that are granted in a single top off.
     * @type {number}
     * @memberof CreditTopOffPlan
     */
    grantAmount: number;
    /**
     * Price for the grant, in lowest denomination (i.e cents).
     * @type {number}
     * @memberof CreditTopOffPlan
     */
    price: number;
    /**
     * Time length of the default expiration for credits granted in a top off.
     * @type {number}
     * @memberof CreditTopOffPlan
     */
    expirationLength?: number | null;
    /**
     * Time length unit for the default expiration for credits granted in a top off.
     * @type {string}
     * @memberof CreditTopOffPlan
     */
    expirationUnit?: string | null;
    /**
     * A description that will be used on the invoice line items.
     * @type {string}
     * @memberof CreditTopOffPlan
     */
    description?: string | null;
    /**
     * Whether to charge the customer immediately when the top off is triggered.
     * @type {boolean}
     * @memberof CreditTopOffPlan
     */
    chargeImmediately?: boolean;
    /**
     * Whether to add the grants immediately to the credit ledger or wait until either the corresponding invoice is paid or the grant is manually added to the ledger. When charge_immediately is true, this field has no impact since the credits will be granted only after successful payment.
     * @type {boolean}
     * @memberof CreditTopOffPlan
     */
    grantImmediately?: boolean;
}

export function CreditTopOffPlanFromJSON(json: any): CreditTopOffPlan {
    return CreditTopOffPlanFromJSONTyped(json, false);
}

export function CreditTopOffPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditTopOffPlan {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'triggerAmount': json['trigger_amount'],
        'grantAmount': json['grant_amount'],
        'price': json['price'],
        'expirationLength': !exists(json, 'expiration_length') ? undefined : json['expiration_length'],
        'expirationUnit': !exists(json, 'expiration_unit') ? undefined : json['expiration_unit'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'chargeImmediately': !exists(json, 'charge_immediately') ? undefined : json['charge_immediately'],
        'grantImmediately': !exists(json, 'grant_immediately') ? undefined : json['grant_immediately'],
    };
}

export function CreditTopOffPlanToJSON(value?: CreditTopOffPlan | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'trigger_amount': value.triggerAmount,
        'grant_amount': value.grantAmount,
        'price': value.price,
        'expiration_length': value.expirationLength,
        'expiration_unit': value.expirationUnit,
        'description': value.description,
        'charge_immediately': value.chargeImmediately,
        'grant_immediately': value.grantImmediately,
    };
}

