/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditGrant
 */
export interface CreditGrant {
    /**
     * A unique identifier for this grant
     * @type {string}
     * @memberof CreditGrant
     */
    uuid?: string;
    /**
     * The source of the grant.
     * @type {string}
     * @memberof CreditGrant
     */
    source?: string;
    /**
     * Total price paid for the credits, in cents
     * @type {number}
     * @memberof CreditGrant
     */
    price?: number;
    /**
     * Name of the customer who received the grant
     * @type {string}
     * @memberof CreditGrant
     */
    customerName?: string;
    /**
     * The date at which this grant expires
     * @type {Date}
     * @memberof CreditGrant
     */
    expiresAt?: Date;
    /**
     * Number of credits granted
     * @type {number}
     * @memberof CreditGrant
     */
    amount?: number;
    /**
     * Optional description. This is only viewable internally
     * @type {string}
     * @memberof CreditGrant
     */
    description?: string;
    /**
     * The date at which this grant is effective
     * @type {Date}
     * @memberof CreditGrant
     */
    effectiveAt?: Date;
}

export function CreditGrantFromJSON(json: any): CreditGrant {
    return CreditGrantFromJSONTyped(json, false);
}

export function CreditGrantFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditGrant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'source': !exists(json, 'source') ? undefined : json['source'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'customerName': !exists(json, 'customer_name') ? undefined : json['customer_name'],
        'expiresAt': !exists(json, 'expires_at') ? undefined : (new Date(json['expires_at'])),
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'effectiveAt': !exists(json, 'effective_at') ? undefined : (new Date(json['effective_at'])),
    };
}

export function CreditGrantToJSON(value?: CreditGrant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'source': value.source,
        'price': value.price,
        'customer_name': value.customerName,
        'expires_at': value.expiresAt === undefined ? undefined : (value.expiresAt.toISOString()),
        'amount': value.amount,
        'description': value.description,
        'effective_at': value.effectiveAt === undefined ? undefined : (value.effectiveAt.toISOString()),
    };
}

