/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccruedRevenueLineItem,
    AccruedRevenueLineItemFromJSON,
    AccruedRevenueLineItemFromJSONTyped,
    AccruedRevenueLineItemToJSON,
} from './AccruedRevenueLineItem';

/**
 * 
 * @export
 * @interface CustomerSpendByTime
 */
export interface CustomerSpendByTime {
    /**
     * 
     * @type {Array<AccruedRevenueLineItem>}
     * @memberof CustomerSpendByTime
     */
    lineItems?: Array<AccruedRevenueLineItem>;
    /**
     * The end time of this time period till when the spend is computed
     * @type {Date}
     * @memberof CustomerSpendByTime
     */
    endTime?: Date;
    /**
     * Total spend for the time period in cents.
     * @type {number}
     * @memberof CustomerSpendByTime
     */
    totalSpend?: number;
    /**
     * The start time of this time period for which the spend is computed
     * @type {Date}
     * @memberof CustomerSpendByTime
     */
    startTime?: Date;
}

export function CustomerSpendByTimeFromJSON(json: any): CustomerSpendByTime {
    return CustomerSpendByTimeFromJSONTyped(json, false);
}

export function CustomerSpendByTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerSpendByTime {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lineItems': !exists(json, 'line_items') ? undefined : ((json['line_items'] as Array<any>).map(AccruedRevenueLineItemFromJSON)),
        'endTime': !exists(json, 'end_time') ? undefined : (new Date(json['end_time'])),
        'totalSpend': !exists(json, 'total_spend') ? undefined : json['total_spend'],
        'startTime': !exists(json, 'start_time') ? undefined : (new Date(json['start_time'])),
    };
}

export function CustomerSpendByTimeToJSON(value?: CustomerSpendByTime | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'line_items': value.lineItems === undefined ? undefined : ((value.lineItems as Array<any>).map(AccruedRevenueLineItemToJSON)),
        'end_time': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
        'total_spend': value.totalSpend,
        'start_time': value.startTime === undefined ? undefined : (value.startTime.toISOString()),
    };
}

