/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerCreditBalance
 */
export interface CustomerCreditBalance {
    /**
     * Ledger credit balance (i.e., excludes accrued revenue that has not yet been invoiced).
     * @type {number}
     * @memberof CustomerCreditBalance
     */
    ledgerBalance?: number;
    /**
     * Available credit balance.
     * @type {number}
     * @memberof CustomerCreditBalance
     */
    availableBalance?: number;
    /**
     * The cycle start of the billing cycle for which the accrued revenue is computed
     * @type {Date}
     * @memberof CustomerCreditBalance
     */
    startTime?: Date;
    /**
     * The end time within the billing cycle for which this accrued revenue is computed
     * @type {Date}
     * @memberof CustomerCreditBalance
     */
    endTime?: Date;
}

export function CustomerCreditBalanceFromJSON(json: any): CustomerCreditBalance {
    return CustomerCreditBalanceFromJSONTyped(json, false);
}

export function CustomerCreditBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerCreditBalance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ledgerBalance': !exists(json, 'ledger_balance') ? undefined : json['ledger_balance'],
        'availableBalance': !exists(json, 'available_balance') ? undefined : json['available_balance'],
        'startTime': !exists(json, 'start_time') ? undefined : (new Date(json['start_time'])),
        'endTime': !exists(json, 'end_time') ? undefined : (new Date(json['end_time'])),
    };
}

export function CustomerCreditBalanceToJSON(value?: CustomerCreditBalance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ledger_balance': value.ledgerBalance,
        'available_balance': value.availableBalance,
        'start_time': value.startTime === undefined ? undefined : (value.startTime.toISOString()),
        'end_time': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
    };
}

