/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerStatus
 */
export interface CustomerStatus {
    /**
     * 
     * @type {string}
     * @memberof CustomerStatus
     */
    status?: string;
}

export function CustomerStatusFromJSON(json: any): CustomerStatus {
    return CustomerStatusFromJSONTyped(json, false);
}

export function CustomerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function CustomerStatusToJSON(value?: CustomerStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}

