/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerPortalContactInfoInputArgs
 */
export interface CustomerPortalContactInfoInputArgs {
    /**
     * 
     * @type {string}
     * @memberof CustomerPortalContactInfoInputArgs
     */
    zipcode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPortalContactInfoInputArgs
     */
    legalName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPortalContactInfoInputArgs
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPortalContactInfoInputArgs
     */
    phone?: string | null;
    /**
     * Customer name. Required only if using vendor API Key for authentication.
     * @type {string}
     * @memberof CustomerPortalContactInfoInputArgs
     */
    customerName?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerPortalContactInfoInputArgs
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPortalContactInfoInputArgs
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPortalContactInfoInputArgs
     */
    vatId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPortalContactInfoInputArgs
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPortalContactInfoInputArgs
     */
    logoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPortalContactInfoInputArgs
     */
    addressLine2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPortalContactInfoInputArgs
     */
    addressLine1?: string | null;
    /**
     * List of secondary contact emails (all email communication will also be sent to these emails).
     * @type {Array<string>}
     * @memberof CustomerPortalContactInfoInputArgs
     */
    secondaryEmails?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPortalContactInfoInputArgs
     */
    url?: string | null;
}

export function CustomerPortalContactInfoInputArgsFromJSON(json: any): CustomerPortalContactInfoInputArgs {
    return CustomerPortalContactInfoInputArgsFromJSONTyped(json, false);
}

export function CustomerPortalContactInfoInputArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerPortalContactInfoInputArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'zipcode': !exists(json, 'zipcode') ? undefined : json['zipcode'],
        'legalName': !exists(json, 'legal_name') ? undefined : json['legal_name'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'customerName': !exists(json, 'customer_name') ? undefined : json['customer_name'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'vatId': !exists(json, 'vat_id') ? undefined : json['vat_id'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'logoUrl': !exists(json, 'logo_url') ? undefined : json['logo_url'],
        'addressLine2': !exists(json, 'address_line_2') ? undefined : json['address_line_2'],
        'addressLine1': !exists(json, 'address_line_1') ? undefined : json['address_line_1'],
        'secondaryEmails': !exists(json, 'secondary_emails') ? undefined : json['secondary_emails'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function CustomerPortalContactInfoInputArgsToJSON(value?: CustomerPortalContactInfoInputArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'zipcode': value.zipcode,
        'legal_name': value.legalName,
        'state': value.state,
        'phone': value.phone,
        'customer_name': value.customerName,
        'country': value.country,
        'email': value.email,
        'vat_id': value.vatId,
        'city': value.city,
        'logo_url': value.logoUrl,
        'address_line_2': value.addressLine2,
        'address_line_1': value.addressLine1,
        'secondary_emails': value.secondaryEmails,
        'url': value.url,
    };
}

