/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerPortalSubscriptionInputArgs
 */
export interface CustomerPortalSubscriptionInputArgs {
    /**
     * Price plan name to subscribe to.
     * @type {string}
     * @memberof CustomerPortalSubscriptionInputArgs
     */
    pricePlanName?: string;
    /**
     * Customer name. Required only if using vendor API Key for authentication.
     * @type {string}
     * @memberof CustomerPortalSubscriptionInputArgs
     */
    customerName?: string;
}

export function CustomerPortalSubscriptionInputArgsFromJSON(json: any): CustomerPortalSubscriptionInputArgs {
    return CustomerPortalSubscriptionInputArgsFromJSONTyped(json, false);
}

export function CustomerPortalSubscriptionInputArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerPortalSubscriptionInputArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pricePlanName': !exists(json, 'price_plan_name') ? undefined : json['price_plan_name'],
        'customerName': !exists(json, 'customer_name') ? undefined : json['customer_name'],
    };
}

export function CustomerPortalSubscriptionInputArgsToJSON(value?: CustomerPortalSubscriptionInputArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'price_plan_name': value.pricePlanName,
        'customer_name': value.customerName,
    };
}

