/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomerPortalInvoiceStatus,
    CustomerPortalInvoiceStatusFromJSON,
    CustomerPortalInvoiceStatusFromJSONTyped,
    CustomerPortalInvoiceStatusToJSON,
} from './CustomerPortalInvoiceStatus';
import {
    LineItems,
    LineItemsFromJSON,
    LineItemsFromJSONTyped,
    LineItemsToJSON,
} from './LineItems';

/**
 * 
 * @export
 * @interface CustomerPortalInvoice
 */
export interface CustomerPortalInvoice {
    /**
     * Amount due before any credits are applied
     * @type {number}
     * @memberof CustomerPortalInvoice
     */
    subTotal?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerPortalInvoice
     */
    id?: string;
    /**
     * False if not paid yet
     * @type {boolean}
     * @memberof CustomerPortalInvoice
     */
    isPaid?: boolean;
    /**
     * The date the invoice will be issued to the end customer or forwarded to the payment processor.
     * @type {Date}
     * @memberof CustomerPortalInvoice
     */
    issueDate?: Date;
    /**
     * Any discount credits applied to the invoice
     * @type {number}
     * @memberof CustomerPortalInvoice
     */
    discountCredit?: number;
    /**
     * Information related to the current status of this invoice.
     * @type {CustomerPortalInvoiceStatus}
     * @memberof CustomerPortalInvoice
     */
    status?: CustomerPortalInvoiceStatus | null;
    /**
     * Earliest start time of line items covered by the invoice
     * @type {Date}
     * @memberof CustomerPortalInvoice
     */
    minItemStartTime?: Date;
    /**
     * [DEPRECATED] End time of the cycle in which the invoice was generated
     * @type {Date}
     * @memberof CustomerPortalInvoice
     */
    endTime?: Date;
    /**
     * [DEPRECATED] Start time of the cycle in which the invoice was generated
     * @type {Date}
     * @memberof CustomerPortalInvoice
     */
    startTime?: Date;
    /**
     * Url pointing to the pdf of this invoice.
     * @type {string}
     * @memberof CustomerPortalInvoice
     */
    pdfUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomerPortalInvoice
     */
    dueDate?: Date;
    /**
     * Tax amount applied to subtotal
     * @type {number}
     * @memberof CustomerPortalInvoice
     */
    taxAmount?: number;
    /**
     * Latest end time of line items covered by the invoice
     * @type {Date}
     * @memberof CustomerPortalInvoice
     */
    maxItemEndTime?: Date;
    /**
     * Total amount due
     * @type {number}
     * @memberof CustomerPortalInvoice
     */
    amountDue?: number;
    /**
     * 
     * @type {Array<LineItems>}
     * @memberof CustomerPortalInvoice
     */
    lineItems?: Array<LineItems>;
}

export function CustomerPortalInvoiceFromJSON(json: any): CustomerPortalInvoice {
    return CustomerPortalInvoiceFromJSONTyped(json, false);
}

export function CustomerPortalInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerPortalInvoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subTotal': !exists(json, 'sub_total') ? undefined : json['sub_total'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'isPaid': !exists(json, 'is_paid') ? undefined : json['is_paid'],
        'issueDate': !exists(json, 'issue_date') ? undefined : (new Date(json['issue_date'])),
        'discountCredit': !exists(json, 'discount_credit') ? undefined : json['discount_credit'],
        'status': !exists(json, 'status') ? undefined : CustomerPortalInvoiceStatusFromJSON(json['status']),
        'minItemStartTime': !exists(json, 'min_item_start_time') ? undefined : (new Date(json['min_item_start_time'])),
        'endTime': !exists(json, 'end_time') ? undefined : (new Date(json['end_time'])),
        'startTime': !exists(json, 'start_time') ? undefined : (new Date(json['start_time'])),
        'pdfUrl': !exists(json, 'pdf_url') ? undefined : json['pdf_url'],
        'dueDate': !exists(json, 'due_date') ? undefined : (new Date(json['due_date'])),
        'taxAmount': !exists(json, 'tax_amount') ? undefined : json['tax_amount'],
        'maxItemEndTime': !exists(json, 'max_item_end_time') ? undefined : (new Date(json['max_item_end_time'])),
        'amountDue': !exists(json, 'amount_due') ? undefined : json['amount_due'],
        'lineItems': !exists(json, 'line_items') ? undefined : ((json['line_items'] as Array<any>).map(LineItemsFromJSON)),
    };
}

export function CustomerPortalInvoiceToJSON(value?: CustomerPortalInvoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sub_total': value.subTotal,
        'id': value.id,
        'is_paid': value.isPaid,
        'issue_date': value.issueDate === undefined ? undefined : (value.issueDate.toISOString()),
        'discount_credit': value.discountCredit,
        'status': CustomerPortalInvoiceStatusToJSON(value.status),
        'min_item_start_time': value.minItemStartTime === undefined ? undefined : (value.minItemStartTime.toISOString()),
        'end_time': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
        'start_time': value.startTime === undefined ? undefined : (value.startTime.toISOString()),
        'pdf_url': value.pdfUrl,
        'due_date': value.dueDate === undefined ? undefined : (value.dueDate.toISOString()),
        'tax_amount': value.taxAmount,
        'max_item_end_time': value.maxItemEndTime === undefined ? undefined : (value.maxItemEndTime.toISOString()),
        'amount_due': value.amountDue,
        'line_items': value.lineItems === undefined ? undefined : ((value.lineItems as Array<any>).map(LineItemsToJSON)),
    };
}

