/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomerLabelLimit,
    CustomerLabelLimitFromJSON,
    CustomerLabelLimitFromJSONTyped,
    CustomerLabelLimitToJSON,
} from './CustomerLabelLimit';

/**
 * 
 * @export
 * @interface CustomerFeature
 */
export interface CustomerFeature {
    /**
     * 
     * @type {boolean}
     * @memberof CustomerFeature
     */
    enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CustomerFeature
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerFeature
     */
    limit?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerFeature
     */
    featureName?: string;
    /**
     * 
     * @type {Array<CustomerLabelLimit>}
     * @memberof CustomerFeature
     */
    labelLimits?: Array<CustomerLabelLimit>;
}

export function CustomerFeatureFromJSON(json: any): CustomerFeature {
    return CustomerFeatureFromJSONTyped(json, false);
}

export function CustomerFeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerFeature {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'featureName': !exists(json, 'feature_name') ? undefined : json['feature_name'],
        'labelLimits': !exists(json, 'label_limits') ? undefined : ((json['label_limits'] as Array<any>).map(CustomerLabelLimitFromJSON)),
    };
}

export function CustomerFeatureToJSON(value?: CustomerFeature | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'quantity': value.quantity,
        'limit': value.limit,
        'feature_name': value.featureName,
        'label_limits': value.labelLimits === undefined ? undefined : ((value.labelLimits as Array<any>).map(CustomerLabelLimitToJSON)),
    };
}

