/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DailyUsage
 */
export interface DailyUsage {
    /**
     * Total usage during this window.
     * @type {number}
     * @memberof DailyUsage
     */
    usage?: number;
    /**
     * Start of the 24 hour time window in UTC.
     * @type {Date}
     * @memberof DailyUsage
     */
    time?: Date;
}

export function DailyUsageFromJSON(json: any): DailyUsage {
    return DailyUsageFromJSONTyped(json, false);
}

export function DailyUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyUsage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'usage': !exists(json, 'usage') ? undefined : json['usage'],
        'time': !exists(json, 'time') ? undefined : (new Date(json['time'])),
    };
}

export function DailyUsageToJSON(value?: DailyUsage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'usage': value.usage,
        'time': value.time === undefined ? undefined : (value.time.toISOString()),
    };
}

