/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccruedRevenueLineItem,
    AccruedRevenueLineItemFromJSON,
    AccruedRevenueLineItemFromJSONTyped,
    AccruedRevenueLineItemToJSON,
} from './AccruedRevenueLineItem';

/**
 * 
 * @export
 * @interface DailyAccruedRevenue
 */
export interface DailyAccruedRevenue {
    /**
     * The date for which this accrued revenue is computed
     * @type {Date}
     * @memberof DailyAccruedRevenue
     */
    date?: Date;
    /**
     * The start time of the billing cycle for which the accrued revenue is computed
     * @type {Date}
     * @memberof DailyAccruedRevenue
     */
    startTime?: Date;
    /**
     * Total accrued revenue for the day in cents
     * @type {number}
     * @memberof DailyAccruedRevenue
     */
    totalAccruedRevenue?: number;
    /**
     * The end time till when the accrued revenue is computed
     * @type {Date}
     * @memberof DailyAccruedRevenue
     */
    endTime?: Date;
    /**
     * 
     * @type {Array<AccruedRevenueLineItem>}
     * @memberof DailyAccruedRevenue
     */
    lineItems?: Array<AccruedRevenueLineItem>;
}

export function DailyAccruedRevenueFromJSON(json: any): DailyAccruedRevenue {
    return DailyAccruedRevenueFromJSONTyped(json, false);
}

export function DailyAccruedRevenueFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyAccruedRevenue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'startTime': !exists(json, 'start_time') ? undefined : (new Date(json['start_time'])),
        'totalAccruedRevenue': !exists(json, 'total_accrued_revenue') ? undefined : json['total_accrued_revenue'],
        'endTime': !exists(json, 'end_time') ? undefined : (new Date(json['end_time'])),
        'lineItems': !exists(json, 'line_items') ? undefined : ((json['line_items'] as Array<any>).map(AccruedRevenueLineItemFromJSON)),
    };
}

export function DailyAccruedRevenueToJSON(value?: DailyAccruedRevenue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'start_time': value.startTime === undefined ? undefined : (value.startTime.toISOString()),
        'total_accrued_revenue': value.totalAccruedRevenue,
        'end_time': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
        'line_items': value.lineItems === undefined ? undefined : ((value.lineItems as Array<any>).map(AccruedRevenueLineItemToJSON)),
    };
}

