/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteDiscountInputArgs
 */
export interface DeleteDiscountInputArgs {
    /**
     * External UUID representing the discount to be deleted.
     * @type {string}
     * @memberof DeleteDiscountInputArgs
     */
    discountUuid: string;
}

export function DeleteDiscountInputArgsFromJSON(json: any): DeleteDiscountInputArgs {
    return DeleteDiscountInputArgsFromJSONTyped(json, false);
}

export function DeleteDiscountInputArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteDiscountInputArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'discountUuid': json['discount_uuid'],
    };
}

export function DeleteDiscountInputArgsToJSON(value?: DeleteDiscountInputArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'discount_uuid': value.discountUuid,
    };
}

