/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureInputArgs
 */
export interface FeatureInputArgs {
    /**
     * 
     * @type {string}
     * @memberof FeatureInputArgs
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureInputArgs
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureInputArgs
     */
    name?: string;
}

export function FeatureInputArgsFromJSON(json: any): FeatureInputArgs {
    return FeatureInputArgsFromJSONTyped(json, false);
}

export function FeatureInputArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureInputArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'displayName': !exists(json, 'display_name') ? undefined : json['display_name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function FeatureInputArgsToJSON(value?: FeatureInputArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'display_name': value.displayName,
        'description': value.description,
        'name': value.name,
    };
}

