/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LineItems
 */
export interface LineItems {
    /**
     * 
     * @type {Date}
     * @memberof LineItems
     */
    startTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof LineItems
     */
    price?: string;
    /**
     * 
     * @type {string}
     * @memberof LineItems
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof LineItems
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof LineItems
     */
    priceInt?: number;
    /**
     * 
     * @type {string}
     * @memberof LineItems
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof LineItems
     */
    endTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof LineItems
     */
    quantityUnit?: string;
    /**
     * 
     * @type {string}
     * @memberof LineItems
     */
    id?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LineItems
     */
    metadata?: { [key: string]: string; };
}

export function LineItemsFromJSON(json: any): LineItems {
    return LineItemsFromJSONTyped(json, false);
}

export function LineItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineItems {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startTime': !exists(json, 'start_time') ? undefined : (new Date(json['start_time'])),
        'price': !exists(json, 'price') ? undefined : json['price'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
        'priceInt': !exists(json, 'price_int') ? undefined : json['price_int'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'endTime': !exists(json, 'end_time') ? undefined : (new Date(json['end_time'])),
        'quantityUnit': !exists(json, 'quantity_unit') ? undefined : json['quantity_unit'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function LineItemsToJSON(value?: LineItems | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start_time': value.startTime === undefined ? undefined : (value.startTime.toISOString()),
        'price': value.price,
        'name': value.name,
        'quantity': value.quantity,
        'price_int': value.priceInt,
        'description': value.description,
        'end_time': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
        'quantity_unit': value.quantityUnit,
        'id': value.id,
        'metadata': value.metadata,
    };
}

