/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MeteredComponentLabelLimitInputArgs,
    MeteredComponentLabelLimitInputArgsFromJSON,
    MeteredComponentLabelLimitInputArgsFromJSONTyped,
    MeteredComponentLabelLimitInputArgsToJSON,
} from './MeteredComponentLabelLimitInputArgs';
import {
    PriceSchemeInputArgs,
    PriceSchemeInputArgsFromJSON,
    PriceSchemeInputArgsFromJSONTyped,
    PriceSchemeInputArgsToJSON,
} from './PriceSchemeInputArgs';

/**
 * 
 * @export
 * @interface MeteredComponentInputArgs
 */
export interface MeteredComponentInputArgs {
    /**
     * Name to be used on invoice.
     * @type {string}
     * @memberof MeteredComponentInputArgs
     */
    displayName?: string;
    /**
     * 
     * @type {number}
     * @memberof MeteredComponentInputArgs
     */
    id?: number;
    /**
     * Numeric limit to set on customer usage for the meter.
     * @type {number}
     * @memberof MeteredComponentInputArgs
     */
    limit?: number;
    /**
     * 
     * @type {PriceSchemeInputArgs}
     * @memberof MeteredComponentInputArgs
     */
    priceScheme?: PriceSchemeInputArgs;
    /**
     * 
     * @type {Array<MeteredComponentLabelLimitInputArgs>}
     * @memberof MeteredComponentInputArgs
     */
    labelLimits?: Array<MeteredComponentLabelLimitInputArgs>;
    /**
     * 
     * @type {number}
     * @memberof MeteredComponentInputArgs
     */
    meterId?: number;
    /**
     * Codename of the meter.
     * @type {string}
     * @memberof MeteredComponentInputArgs
     */
    meterName?: string;
}

export function MeteredComponentInputArgsFromJSON(json: any): MeteredComponentInputArgs {
    return MeteredComponentInputArgsFromJSONTyped(json, false);
}

export function MeteredComponentInputArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeteredComponentInputArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'displayName': !exists(json, 'display_name') ? undefined : json['display_name'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'priceScheme': !exists(json, 'price_scheme') ? undefined : PriceSchemeInputArgsFromJSON(json['price_scheme']),
        'labelLimits': !exists(json, 'label_limits') ? undefined : ((json['label_limits'] as Array<any>).map(MeteredComponentLabelLimitInputArgsFromJSON)),
        'meterId': !exists(json, 'meter_id') ? undefined : json['meter_id'],
        'meterName': !exists(json, 'meter_name') ? undefined : json['meter_name'],
    };
}

export function MeteredComponentInputArgsToJSON(value?: MeteredComponentInputArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'display_name': value.displayName,
        'id': value.id,
        'limit': value.limit,
        'price_scheme': PriceSchemeInputArgsToJSON(value.priceScheme),
        'label_limits': value.labelLimits === undefined ? undefined : ((value.labelLimits as Array<any>).map(MeteredComponentLabelLimitInputArgsToJSON)),
        'meter_id': value.meterId,
        'meter_name': value.meterName,
    };
}

