/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeterInputArgs
 */
export interface MeterInputArgs {
    /**
     * 
     * @type {string}
     * @memberof MeterInputArgs
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof MeterInputArgs
     */
    meterType?: MeterInputArgsMeterTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof MeterInputArgs
     */
    expectedLabels?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MeterInputArgs
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof MeterInputArgs
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MeterInputArgs
     */
    unitName?: string;
    /**
     * 
     * @type {number}
     * @memberof MeterInputArgs
     */
    vendorId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MeterInputArgs
     */
    isIncremental?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof MeterInputArgs
     */
    primaryLabels?: Array<string>;
}

/**
* @export
* @enum {string}
*/
export enum MeterInputArgsMeterTypeEnum {
    Counter = 'COUNTER',
    Gauge = 'GAUGE'
}

export function MeterInputArgsFromJSON(json: any): MeterInputArgs {
    return MeterInputArgsFromJSONTyped(json, false);
}

export function MeterInputArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeterInputArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'displayName': !exists(json, 'display_name') ? undefined : json['display_name'],
        'meterType': !exists(json, 'meter_type') ? undefined : json['meter_type'],
        'expectedLabels': !exists(json, 'expected_labels') ? undefined : json['expected_labels'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'unitName': !exists(json, 'unit_name') ? undefined : json['unit_name'],
        'vendorId': !exists(json, 'vendor_id') ? undefined : json['vendor_id'],
        'isIncremental': !exists(json, 'is_incremental') ? undefined : json['is_incremental'],
        'primaryLabels': !exists(json, 'primary_labels') ? undefined : json['primary_labels'],
    };
}

export function MeterInputArgsToJSON(value?: MeterInputArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'display_name': value.displayName,
        'meter_type': value.meterType,
        'expected_labels': value.expectedLabels,
        'description': value.description,
        'name': value.name,
        'unit_name': value.unitName,
        'vendor_id': value.vendorId,
        'is_incremental': value.isIncremental,
        'primary_labels': value.primaryLabels,
    };
}

