/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectIntegrationMapping
 */
export interface ObjectIntegrationMapping {
    /**
     * The object type to sync.
     * @type {string}
     * @memberof ObjectIntegrationMapping
     */
    objectType: string;
    /**
     * The direction to sync the object in.
     * @type {string}
     * @memberof ObjectIntegrationMapping
     */
    syncType: string;
}

export function ObjectIntegrationMappingFromJSON(json: any): ObjectIntegrationMapping {
    return ObjectIntegrationMappingFromJSONTyped(json, false);
}

export function ObjectIntegrationMappingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectIntegrationMapping {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objectType': json['object_type'],
        'syncType': json['sync_type'],
    };
}

export function ObjectIntegrationMappingToJSON(value?: ObjectIntegrationMapping | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'object_type': value.objectType,
        'sync_type': value.syncType,
    };
}

