/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PastInvoice
 */
export interface PastInvoice {
    /**
     * 
     * @type {string}
     * @memberof PastInvoice
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof PastInvoice
     */
    statusDescription?: string;
    /**
     * 
     * @type {number}
     * @memberof PastInvoice
     */
    amountDue?: number;
    /**
     * 
     * @type {string}
     * @memberof PastInvoice
     */
    exportUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof PastInvoice
     */
    dueDate?: Date;
    /**
     * External unique 'uuid' identifier for this Invoice.
     * @type {string}
     * @memberof PastInvoice
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof PastInvoice
     */
    issueDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof PastInvoice
     */
    customerName?: string;
}

export function PastInvoiceFromJSON(json: any): PastInvoice {
    return PastInvoiceFromJSONTyped(json, false);
}

export function PastInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PastInvoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'statusDescription': !exists(json, 'status_description') ? undefined : json['status_description'],
        'amountDue': !exists(json, 'amount_due') ? undefined : json['amount_due'],
        'exportUrl': !exists(json, 'export_url') ? undefined : json['export_url'],
        'dueDate': !exists(json, 'due_date') ? undefined : (new Date(json['due_date'])),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'issueDate': !exists(json, 'issue_date') ? undefined : (new Date(json['issue_date'])),
        'customerName': !exists(json, 'customer_name') ? undefined : json['customer_name'],
    };
}

export function PastInvoiceToJSON(value?: PastInvoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'status_description': value.statusDescription,
        'amount_due': value.amountDue,
        'export_url': value.exportUrl,
        'due_date': value.dueDate === undefined ? undefined : (value.dueDate.toISOString()),
        'id': value.id,
        'issue_date': value.issueDate === undefined ? undefined : (value.issueDate.toISOString()),
        'customer_name': value.customerName,
    };
}

