/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SelfServePricePlansInputArgs
 */
export interface SelfServePricePlansInputArgs {
    /**
     * 
     * @type {Array<string>}
     * @memberof SelfServePricePlansInputArgs
     */
    pricePlanUuids?: Array<string>;
}

export function SelfServePricePlansInputArgsFromJSON(json: any): SelfServePricePlansInputArgs {
    return SelfServePricePlansInputArgsFromJSONTyped(json, false);
}

export function SelfServePricePlansInputArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelfServePricePlansInputArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pricePlanUuids': !exists(json, 'price_plan_uuids') ? undefined : json['price_plan_uuids'],
    };
}

export function SelfServePricePlansInputArgsToJSON(value?: SelfServePricePlansInputArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'price_plan_uuids': value.pricePlanUuids,
    };
}

