/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SelfServeSettings
 */
export interface SelfServeSettings {
    /**
     * True if the customer can purchase credits via self serve. Defaults to False.
     * @type {boolean}
     * @memberof SelfServeSettings
     */
    purchaseCredits: boolean;
    /**
     * Time length of the default expiration for credits bought in the customer portal.
     * @type {number}
     * @memberof SelfServeSettings
     */
    creditsExpirationLength?: number | null;
    /**
     * Time length unit for the default expiration for credits bought in the customer portal.
     * @type {string}
     * @memberof SelfServeSettings
     */
    creditsExpirationUnit?: string | null;
    /**
     * True if credits should be granted immediately upon purchase. Defaults to True if not set or if `credits_charge_immediately` is True.
     * @type {boolean}
     * @memberof SelfServeSettings
     */
    creditsGrantImmediately?: boolean;
    /**
     * True if credits should be charged immediately upon purchase. Defaults to False.
     * @type {boolean}
     * @memberof SelfServeSettings
     */
    creditsChargeImmediately?: boolean;
    /**
     * True if credits should be voided if the payment fails. Defaults to False.
     * @type {boolean}
     * @memberof SelfServeSettings
     */
    creditsVoidOnPaymentFailure?: boolean;
    /**
     * Price per credit, in cents, that the customer is charged for buying credits through the customer portal
     * @type {number}
     * @memberof SelfServeSettings
     */
    pricePerCreditCents?: number | null;
    /**
     * True if the customer can switch their current price plan via self serve. Defaults to False.
     * @type {boolean}
     * @memberof SelfServeSettings
     */
    switchPricePlans: boolean;
    /**
     * True if payment form should have fields for shipping address info. Defaults to False.
     * @type {boolean}
     * @memberof SelfServeSettings
     */
    enableAddressFields?: boolean;
    /**
     * DEPRECATED: Please use 'customization_settings' as needed.
     * @type {boolean}
     * @memberof SelfServeSettings
     */
    customization?: boolean;
}

export function SelfServeSettingsFromJSON(json: any): SelfServeSettings {
    return SelfServeSettingsFromJSONTyped(json, false);
}

export function SelfServeSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelfServeSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'purchaseCredits': json['purchase_credits'],
        'creditsExpirationLength': !exists(json, 'credits_expiration_length') ? undefined : json['credits_expiration_length'],
        'creditsExpirationUnit': !exists(json, 'credits_expiration_unit') ? undefined : json['credits_expiration_unit'],
        'creditsGrantImmediately': !exists(json, 'credits_grant_immediately') ? undefined : json['credits_grant_immediately'],
        'creditsChargeImmediately': !exists(json, 'credits_charge_immediately') ? undefined : json['credits_charge_immediately'],
        'creditsVoidOnPaymentFailure': !exists(json, 'credits_void_on_payment_failure') ? undefined : json['credits_void_on_payment_failure'],
        'pricePerCreditCents': !exists(json, 'price_per_credit_cents') ? undefined : json['price_per_credit_cents'],
        'switchPricePlans': json['switch_price_plans'],
        'enableAddressFields': !exists(json, 'enable_address_fields') ? undefined : json['enable_address_fields'],
        'customization': !exists(json, 'customization') ? undefined : json['customization'],
    };
}

export function SelfServeSettingsToJSON(value?: SelfServeSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'purchase_credits': value.purchaseCredits,
        'credits_expiration_length': value.creditsExpirationLength,
        'credits_expiration_unit': value.creditsExpirationUnit,
        'credits_grant_immediately': value.creditsGrantImmediately,
        'credits_charge_immediately': value.creditsChargeImmediately,
        'credits_void_on_payment_failure': value.creditsVoidOnPaymentFailure,
        'price_per_credit_cents': value.pricePerCreditCents,
        'switch_price_plans': value.switchPricePlans,
        'enable_address_fields': value.enableAddressFields,
        'customization': value.customization,
    };
}

