/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaxCode
 */
export interface TaxCode {
    /**
     * A code string that identifies this tax code.
     * @type {string}
     * @memberof TaxCode
     */
    taxCode?: string;
    /**
     * The type of this tax code.
     * @type {string}
     * @memberof TaxCode
     */
    taxCodeTypeId?: string;
    /**
     * The unique ID number of this tax code.
     * @type {string}
     * @memberof TaxCode
     */
    id?: string;
    /**
     * A friendly description of this tax code.
     * @type {string}
     * @memberof TaxCode
     */
    description?: string;
    /**
     * The Avalara Entity Use Code represented by this tax code.
     * @type {string}
     * @memberof TaxCode
     */
    entityUseCode?: string;
}

export function TaxCodeFromJSON(json: any): TaxCode {
    return TaxCodeFromJSONTyped(json, false);
}

export function TaxCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxCode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taxCode': !exists(json, 'tax_code') ? undefined : json['tax_code'],
        'taxCodeTypeId': !exists(json, 'tax_code_type_id') ? undefined : json['tax_code_type_id'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'entityUseCode': !exists(json, 'entity_use_code') ? undefined : json['entity_use_code'],
    };
}

export function TaxCodeToJSON(value?: TaxCode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tax_code': value.taxCode,
        'tax_code_type_id': value.taxCodeTypeId,
        'id': value.id,
        'description': value.description,
        'entity_use_code': value.entityUseCode,
    };
}

