/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpcomingInvoice
 */
export interface UpcomingInvoice {
    /**
     * 
     * @type {string}
     * @memberof UpcomingInvoice
     */
    customerName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpcomingInvoice
     */
    exportUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpcomingInvoice
     */
    generateDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpcomingInvoice
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof UpcomingInvoice
     */
    statusDescription?: string;
}

export function UpcomingInvoiceFromJSON(json: any): UpcomingInvoice {
    return UpcomingInvoiceFromJSONTyped(json, false);
}

export function UpcomingInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpcomingInvoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customerName': !exists(json, 'customer_name') ? undefined : json['customer_name'],
        'exportUrl': !exists(json, 'export_url') ? undefined : json['export_url'],
        'generateDate': !exists(json, 'generate_date') ? undefined : (new Date(json['generate_date'])),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'statusDescription': !exists(json, 'status_description') ? undefined : json['status_description'],
    };
}

export function UpcomingInvoiceToJSON(value?: UpcomingInvoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer_name': value.customerName,
        'export_url': value.exportUrl,
        'generate_date': value.generateDate === undefined ? undefined : (value.generateDate.toISOString()),
        'status': value.status,
        'status_description': value.statusDescription,
    };
}

