/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCustomerAvalaraSettingsArgs
 */
export interface UpdateCustomerAvalaraSettingsArgs {
    /**
     * Entity code describing this customer.
     * @type {string}
     * @memberof UpdateCustomerAvalaraSettingsArgs
     */
    entityUseCode?: string;
    /**
     * True if Avalara integration should be enabled for this customer, False otherwise.
     * @type {boolean}
     * @memberof UpdateCustomerAvalaraSettingsArgs
     */
    enableIntegration?: boolean;
    /**
     * Tax exemption number specific to this customer
     * @type {string}
     * @memberof UpdateCustomerAvalaraSettingsArgs
     */
    exemptionNumber?: string;
}

export function UpdateCustomerAvalaraSettingsArgsFromJSON(json: any): UpdateCustomerAvalaraSettingsArgs {
    return UpdateCustomerAvalaraSettingsArgsFromJSONTyped(json, false);
}

export function UpdateCustomerAvalaraSettingsArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCustomerAvalaraSettingsArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entityUseCode': !exists(json, 'entity_use_code') ? undefined : json['entity_use_code'],
        'enableIntegration': !exists(json, 'enable_integration') ? undefined : json['enable_integration'],
        'exemptionNumber': !exists(json, 'exemption_number') ? undefined : json['exemption_number'],
    };
}

export function UpdateCustomerAvalaraSettingsArgsToJSON(value?: UpdateCustomerAvalaraSettingsArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entity_use_code': value.entityUseCode,
        'enable_integration': value.enableIntegration,
        'exemption_number': value.exemptionNumber,
    };
}

