/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DiscountInputArgs,
    DiscountInputArgsFromJSON,
    DiscountInputArgsFromJSONTyped,
    DiscountInputArgsToJSON,
} from './DiscountInputArgs';
import {
    FeatureInputArgs,
    FeatureInputArgsFromJSON,
    FeatureInputArgsFromJSONTyped,
    FeatureInputArgsToJSON,
} from './FeatureInputArgs';
import {
    LimitInputArgs,
    LimitInputArgsFromJSON,
    LimitInputArgsFromJSONTyped,
    LimitInputArgsToJSON,
} from './LimitInputArgs';
import {
    SubscriptionAddOnInput,
    SubscriptionAddOnInputFromJSON,
    SubscriptionAddOnInputFromJSONTyped,
    SubscriptionAddOnInputToJSON,
} from './SubscriptionAddOnInput';
import {
    TrialInputArgs,
    TrialInputArgsFromJSON,
    TrialInputArgsFromJSONTyped,
    TrialInputArgsToJSON,
} from './TrialInputArgs';

/**
 * 
 * @export
 * @interface UpdateSubscriptionArgs
 */
export interface UpdateSubscriptionArgs {
    /**
     * 
     * @type {Array<SubscriptionAddOnInput>}
     * @memberof UpdateSubscriptionArgs
     */
    addOns?: Array<SubscriptionAddOnInput> | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateSubscriptionArgs
     */
    alignToCalendar?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UpdateSubscriptionArgs
     */
    couponOverrideId?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateSubscriptionArgs
     */
    couponOverrideName?: string;
    /**
     * 
     * @type {DiscountInputArgs}
     * @memberof UpdateSubscriptionArgs
     */
    discountOverride?: DiscountInputArgs | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateSubscriptionArgs
     */
    effectiveAt?: Date;
    /**
     * 
     * @type {Array<FeatureInputArgs>}
     * @memberof UpdateSubscriptionArgs
     */
    featuresOverride?: Array<FeatureInputArgs> | null;
    /**
     * 
     * @type {Array<LimitInputArgs>}
     * @memberof UpdateSubscriptionArgs
     */
    limitsOverride?: Array<LimitInputArgs> | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateSubscriptionArgs
     */
    pricePlanId?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateSubscriptionArgs
     */
    pricePlanName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSubscriptionArgs
     */
    pricePlanTag?: string;
    /**
     * 
     * @type {TrialInputArgs}
     * @memberof UpdateSubscriptionArgs
     */
    trialOverride?: TrialInputArgs | null;
}

export function UpdateSubscriptionArgsFromJSON(json: any): UpdateSubscriptionArgs {
    return UpdateSubscriptionArgsFromJSONTyped(json, false);
}

export function UpdateSubscriptionArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSubscriptionArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addOns': !exists(json, 'add_ons') ? undefined : (json['add_ons'] === null ? null : (json['add_ons'] as Array<any>).map(SubscriptionAddOnInputFromJSON)),
        'alignToCalendar': !exists(json, 'align_to_calendar') ? undefined : json['align_to_calendar'],
        'couponOverrideId': !exists(json, 'coupon_override_id') ? undefined : json['coupon_override_id'],
        'couponOverrideName': !exists(json, 'coupon_override_name') ? undefined : json['coupon_override_name'],
        'discountOverride': !exists(json, 'discount_override') ? undefined : DiscountInputArgsFromJSON(json['discount_override']),
        'effectiveAt': !exists(json, 'effective_at') ? undefined : (new Date(json['effective_at'])),
        'featuresOverride': !exists(json, 'features_override') ? undefined : (json['features_override'] === null ? null : (json['features_override'] as Array<any>).map(FeatureInputArgsFromJSON)),
        'limitsOverride': !exists(json, 'limits_override') ? undefined : (json['limits_override'] === null ? null : (json['limits_override'] as Array<any>).map(LimitInputArgsFromJSON)),
        'pricePlanId': !exists(json, 'price_plan_id') ? undefined : json['price_plan_id'],
        'pricePlanName': !exists(json, 'price_plan_name') ? undefined : json['price_plan_name'],
        'pricePlanTag': !exists(json, 'price_plan_tag') ? undefined : json['price_plan_tag'],
        'trialOverride': !exists(json, 'trial_override') ? undefined : TrialInputArgsFromJSON(json['trial_override']),
    };
}

export function UpdateSubscriptionArgsToJSON(value?: UpdateSubscriptionArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'add_ons': value.addOns === undefined ? undefined : (value.addOns === null ? null : (value.addOns as Array<any>).map(SubscriptionAddOnInputToJSON)),
        'align_to_calendar': value.alignToCalendar,
        'coupon_override_id': value.couponOverrideId,
        'coupon_override_name': value.couponOverrideName,
        'discount_override': DiscountInputArgsToJSON(value.discountOverride),
        'effective_at': value.effectiveAt === undefined ? undefined : (value.effectiveAt.toISOString()),
        'features_override': value.featuresOverride === undefined ? undefined : (value.featuresOverride === null ? null : (value.featuresOverride as Array<any>).map(FeatureInputArgsToJSON)),
        'limits_override': value.limitsOverride === undefined ? undefined : (value.limitsOverride === null ? null : (value.limitsOverride as Array<any>).map(LimitInputArgsToJSON)),
        'price_plan_id': value.pricePlanId,
        'price_plan_name': value.pricePlanName,
        'price_plan_tag': value.pricePlanTag,
        'trial_override': TrialInputArgsToJSON(value.trialOverride),
    };
}

