/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateVendorAvalaraSettingsArgs
 */
export interface UpdateVendorAvalaraSettingsArgs {
    /**
     * The Avalara company code string to associate the Octane vendor with.
     * @type {string}
     * @memberof UpdateVendorAvalaraSettingsArgs
     */
    companyCode?: string;
    /**
     * The item description to use to represent all the lines on the Octane invoice.
     * @type {string}
     * @memberof UpdateVendorAvalaraSettingsArgs
     */
    itemDescription?: string;
    /**
     * The Avalara item code to use to represent all the line items on the Octane invoice.
     * @type {string}
     * @memberof UpdateVendorAvalaraSettingsArgs
     */
    itemCode?: string;
    /**
     * True if the documents generated in Avalara should be committed, false otherwise.
     * @type {boolean}
     * @memberof UpdateVendorAvalaraSettingsArgs
     */
    commitDocuments?: boolean;
    /**
     * True if enabling logging for Avalara calls, false otherwise.
     * @type {boolean}
     * @memberof UpdateVendorAvalaraSettingsArgs
     */
    enableLogging?: boolean;
    /**
     * he tax code to associate with the item that is representing the Octane invoice.
     * @type {string}
     * @memberof UpdateVendorAvalaraSettingsArgs
     */
    taxCode?: string;
    /**
     * Enable/Disable the Avalara integration.
     * @type {boolean}
     * @memberof UpdateVendorAvalaraSettingsArgs
     */
    enableIntegration?: boolean;
}

export function UpdateVendorAvalaraSettingsArgsFromJSON(json: any): UpdateVendorAvalaraSettingsArgs {
    return UpdateVendorAvalaraSettingsArgsFromJSONTyped(json, false);
}

export function UpdateVendorAvalaraSettingsArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateVendorAvalaraSettingsArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'companyCode': !exists(json, 'company_code') ? undefined : json['company_code'],
        'itemDescription': !exists(json, 'item_description') ? undefined : json['item_description'],
        'itemCode': !exists(json, 'item_code') ? undefined : json['item_code'],
        'commitDocuments': !exists(json, 'commit_documents') ? undefined : json['commit_documents'],
        'enableLogging': !exists(json, 'enable_logging') ? undefined : json['enable_logging'],
        'taxCode': !exists(json, 'tax_code') ? undefined : json['tax_code'],
        'enableIntegration': !exists(json, 'enable_integration') ? undefined : json['enable_integration'],
    };
}

export function UpdateVendorAvalaraSettingsArgsToJSON(value?: UpdateVendorAvalaraSettingsArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company_code': value.companyCode,
        'item_description': value.itemDescription,
        'item_code': value.itemCode,
        'commit_documents': value.commitDocuments,
        'enable_logging': value.enableLogging,
        'tax_code': value.taxCode,
        'enable_integration': value.enableIntegration,
    };
}

