/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCustomerQuickbooksConfigurationArgs
 */
export interface UpdateCustomerQuickbooksConfigurationArgs {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCustomerQuickbooksConfigurationArgs
     */
    enabled?: boolean;
}

export function UpdateCustomerQuickbooksConfigurationArgsFromJSON(json: any): UpdateCustomerQuickbooksConfigurationArgs {
    return UpdateCustomerQuickbooksConfigurationArgsFromJSONTyped(json, false);
}

export function UpdateCustomerQuickbooksConfigurationArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCustomerQuickbooksConfigurationArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function UpdateCustomerQuickbooksConfigurationArgsToJSON(value?: UpdateCustomerQuickbooksConfigurationArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
    };
}

