/* tslint:disable */
/* eslint-disable */
/**
 * Octane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCustomerPortalSettingsInputArgs
 */
export interface UpdateCustomerPortalSettingsInputArgs {
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomerPortalSettingsInputArgs
     */
    pricePlanNamesFilter?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomerPortalSettingsInputArgs
     */
    pricePlanTagsFilter?: string;
}

export function UpdateCustomerPortalSettingsInputArgsFromJSON(json: any): UpdateCustomerPortalSettingsInputArgs {
    return UpdateCustomerPortalSettingsInputArgsFromJSONTyped(json, false);
}

export function UpdateCustomerPortalSettingsInputArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCustomerPortalSettingsInputArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pricePlanNamesFilter': !exists(json, 'price_plan_names_filter') ? undefined : json['price_plan_names_filter'],
        'pricePlanTagsFilter': !exists(json, 'price_plan_tags_filter') ? undefined : json['price_plan_tags_filter'],
    };
}

export function UpdateCustomerPortalSettingsInputArgsToJSON(value?: UpdateCustomerPortalSettingsInputArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'price_plan_names_filter': value.pricePlanNamesFilter,
        'price_plan_tags_filter': value.pricePlanTagsFilter,
    };
}

