name: release
on:
  push:
    tags: ["*"]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Build octane-node
        run: |
          npm install
          npm run-script test
      - name: Release package to npmjs
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTOMATION_TOKEN }}
